### ISSUE TITLE
none of your tests pass

### ISSUE THREAD

**Issue by markuz-brasil** [FamousTools/famous-dist-generator#6]
nada

**Comment by jd-carroll** [comment]
I am seeing something similar.

```
    # tests 203
    # pass  6
    # fail  197

total ................................................ 14/232
```

What's more strange is that I get the same numbers both before and after the fix for #7 and #8.  My guess is that one of the tests is wrong or does something to the environment/filesystem that causes everything else to fail.

I've uploaded my test output to: https://github.com/jd-carroll/famous-dist-generator/blob/test-errors/test/tests.log

I'll see if I can look into this some later this week.

**Comment by TheAlphaNerd** [comment]
Hey @markuz-brasil it has been some time.  I just wanted to let you know that the dist generator has been completely rebuilt from the ground up and should hopefully work on your machine without any issues.

**Comment by markuz-brasil** [comment]
Thanks, but now that the npm package is commonjs, I guess my need for it is
not that important.

Again, thanks for your time
